SUMMARY = "Dweepy is a simple Python client for dweet.io. Dweepy has a full test suite and aims to have 100% coverage of the dweet.io API."
HOMEPAGE = "https://github.com/paddycarey/dweepy"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=66c0e0f1d36206e62739ba8d54071924"

SRC_URI[md5sum] = "5ad51670567eec55f578fdc2583e93db"
SRC_URI[sha256sum] = "a89730cb2e924cb4cd9bafb605874baf6f709cd42ce141407cda6e0f8815e5f3"
